# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3044b6d82fe3cb54b664cc0c627534a23738a0f0480f567147c584bbeba0033512ec158d2d4f2abbbea579cad9b2f7d89580eb65827189865a494910030ee5c3

test:
  secret_key_base: be1fdf2a0c0034e83d5fbc36434cd3c59bbbc186370a00db7ab3498aeb066d8d3bb3703b13bc6a198d8944d43e4dc21dfe5301779cb37956dea114e39eb3c030

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
